/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Dell
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnGestionInventario = new javax.swing.JButton();
        BtnPuntosVenta = new javax.swing.JButton();
        BtnRegistroPedido = new javax.swing.JButton();
        BtnReporteVentas = new javax.swing.JButton();
        BtnGestionPersonal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image11.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 160, 70));

        BtnGestionInventario.setBackground(new java.awt.Color(255, 204, 0));
        BtnGestionInventario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnGestionInventario.setText("Gestión de Inventario ");
        BtnGestionInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGestionInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 150, 30));

        BtnPuntosVenta.setBackground(new java.awt.Color(255, 204, 0));
        BtnPuntosVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPuntosVenta.setText("Puntos de Venta");
        BtnPuntosVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPuntosVentaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPuntosVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, 30));

        BtnRegistroPedido.setBackground(new java.awt.Color(255, 204, 0));
        BtnRegistroPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnRegistroPedido.setText("Registro de Pedido");
        BtnRegistroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistroPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, 30));

        BtnReporteVentas.setBackground(new java.awt.Color(255, 204, 0));
        BtnReporteVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnReporteVentas.setText("Reporte de Ventas");
        BtnReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReporteVentasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnReporteVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 150, 30));

        BtnGestionPersonal.setBackground(new java.awt.Color(255, 204, 0));
        BtnGestionPersonal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnGestionPersonal.setText("Gestión de Personal");
        BtnGestionPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGestionPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 150, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("La Preferida de Cajeme");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGestionInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGestionInventarioActionPerformed

    private void BtnPuntosVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPuntosVentaActionPerformed
    // Crear una nueva instancia de FrmPuntosVenta
    FrmPuntosVenta puntosVenta = new FrmPuntosVenta();
    
    // Hacer visible la ventana FrmPuntosVenta
    puntosVenta.setVisible(true);
    
   
    this.dispose(); // Cierra el FrmMenu
    this.setVisible(false); // Solo oculta el FrmMenu
    }//GEN-LAST:event_BtnPuntosVentaActionPerformed

    private void BtnRegistroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroPedidoActionPerformed
    // Crear una nueva instancia de FrmPuntosVenta
    FrmRegistroPedido registroPedido = new FrmRegistroPedido();
    
    // Hacer visible la ventana FrmPuntosVenta
    registroPedido.setVisible(true);
    
   
    this.dispose(); // Cierra el FrmMenu
    this.setVisible(false); // Solo oculta el FrmMenu
    }//GEN-LAST:event_BtnRegistroPedidoActionPerformed

    private void BtnReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReporteVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnReporteVentasActionPerformed

    private void BtnGestionPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGestionPersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGestionInventario;
    private javax.swing.JButton BtnGestionPersonal;
    private javax.swing.JButton BtnPuntosVenta;
    private javax.swing.JButton BtnRegistroPedido;
    private javax.swing.JButton BtnReporteVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
